services:
  - type: web
    name: my-streamlit-app
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr poppler-utils
      pip install -r requirements.txt
    startCommand: streamlit run main.py
    region: us
